sonar.projectKey=dummy-laravel
sonar.projectName=dummy-laravel
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**
# sonar.javascript.lcov.reportPaths=coverage/lcov.info